Features/tetriminos 02
LekZ974/red-tetris pull request #7
Opened 2018-07-12 20:37 UTC by Graziellah

Need some helps for events implementation

2018-07-13 09:27 UTC, LekZ974 requested changes

2018-07-13 09:27 UTC, LekZ974 commented on src/client/components/Room/PlayGround.js
> +      this.handleKeyDown = this.handleKeyDown.bind(this)
this et bind interdit non?

2018-07-13 09:27 UTC, LekZ974 commented on src/client/containers/view/Room.js
> +    name:"Alenxande",
"Alexandre"! ;)

2018-07-13 09:27 UTC, LekZ974 commented on src/client/components/Room/PlayGround.js
> +        () => this.setState({tetriminosPosY: this.state.tetriminosPosY + 48}),
this?

2018-07-13 09:27 UTC, LekZ974 commented on src/client/components/Room/PlayGround.js
> +                posX={this.state.tetriminosPosX}
this

2018-07-13 12:28 UTC, Graziellah commented on src/client/components/Room/PlayGround.js
> +      this.handleKeyDown = this.handleKeyDown.bind(this)
Oui je sais mais j'essaie deja de la faire fonctionner

2018-07-13 12:29 UTC, Graziellah commented on src/client/containers/view/Room.js
> +    name:"Alenxande",
lol, dsl

2018-09-17 16:58 UTC, Graziellah commented
conflict resolved

2018-09-24 11:48 UTC, closed without merging